"""SQLAlchemy ORM models — the source of truth for the SQLite schema.

Schema layout follows the design doc §14 verbatim. Field-by-field changes
must be accompanied by an alembic migration; do not edit existing
declarations here without one. New tables and indexes also belong in a new
migration revision so production data survives.

Conventions used here:
- All primary keys for entities are TEXT prefixed IDs (``u_``, ``j_``,
  ``set_``, ``img_``, ``sess_``, ``ann_``) per design doc Appendix B; they
  are generated by ``app.utils.ids`` (added in PR-08).
- Timestamps default to ``CURRENT_TIMESTAMP`` server-side. SQLite stores
  them as ISO 8601 strings; SQLAlchemy translates to Python ``datetime``.
- All TEXT columns are unicode; SQLite is encoding-agnostic but we treat
  them as UTF-8 by convention.
- ``CHECK`` constraints encode invariants the application also enforces;
  duplicating them at the DB level keeps the schema self-describing and
  catches programming errors during development.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    PrimaryKeyConstraint,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Single declarative base for every ORM model in the project."""

    pass


# ---------------------------------------------------------------------------
# Users / tiers
# ---------------------------------------------------------------------------


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    username: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    tier: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'active'")
    )
    display_name: Mapped[str | None] = mapped_column(Text, nullable=True)

    today_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    today_reset_date: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("(date('now','+8 hours'))")
    )

    override_soft_quota: Mapped[int | None] = mapped_column(Integer, nullable=True)
    override_hard_quota: Mapped[int | None] = mapped_column(Integer, nullable=True)

    last_seq_no: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )

    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    last_login_at: Mapped[datetime | None] = mapped_column(nullable=True)

    __table_args__ = (
        CheckConstraint("role IN ('admin','user')", name="ck_users_role"),
        CheckConstraint(
            "status IN ('active','disabled','deleted')", name="ck_users_status"
        ),
        Index("idx_users_status_tier", "status", "tier"),
    )


class Tier(Base):
    __tablename__ = "tiers"

    tier: Mapped[str] = mapped_column(Text, primary_key=True)
    weight: Mapped[int] = mapped_column(Integer, nullable=False)
    max_concurrency: Mapped[int] = mapped_column(Integer, nullable=False)
    max_queue: Mapped[int] = mapped_column(Integer, nullable=False)
    soft_quota: Mapped[int] = mapped_column(Integer, nullable=False)
    hard_quota: Mapped[int] = mapped_column(Integer, nullable=False)
    slo_p95_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (
        CheckConstraint(
            "tier IN ('vip','premium','standard','free')", name="ck_tiers_tier"
        ),
    )


# ---------------------------------------------------------------------------
# Providers (relay stations) and per-(provider, model) capability tables
# ---------------------------------------------------------------------------


class Provider(Base):
    __tablename__ = "providers"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    label: Mapped[str] = mapped_column(Text, nullable=False)
    adapter_type: Mapped[str] = mapped_column(Text, nullable=False)
    base_url: Mapped[str] = mapped_column(Text, nullable=False)
    # AES-GCM encrypted; never store the cleartext key.
    api_key_enc: Mapped[str] = mapped_column(Text, nullable=False)
    cost_per_image_cny: Mapped[float] = mapped_column(nullable=False)
    initial_balance_cny: Mapped[float] = mapped_column(nullable=False)
    balance_cny: Mapped[float] = mapped_column(nullable=False)

    enabled: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1")
    )
    note: Mapped[str | None] = mapped_column(Text, nullable=True)

    max_concurrency: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("10")
    )
    rpm_limit: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("600")
    )

    circuit_state: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'healthy'")
    )
    cooldown_until: Mapped[datetime | None] = mapped_column(nullable=True)
    # Snapshot of the in-memory metric ring buffer; refreshed periodically
    # so admin views can display recent activity without hitting the live
    # MetricsEngine.
    recent_calls_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (
        CheckConstraint(
            "circuit_state IN ('healthy','open','half_open','drained','disabled')",
            name="ck_providers_circuit_state",
        ),
    )


class ProviderModel(Base):
    __tablename__ = "provider_models"

    provider_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("providers.id", ondelete="CASCADE"),
        nullable=False,
    )
    model_id: Mapped[str] = mapped_column(Text, nullable=False)
    capabilities_json: Mapped[str] = mapped_column(Text, nullable=False)
    enabled: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1")
    )

    __table_args__ = (
        PrimaryKeyConstraint("provider_id", "model_id", name="pk_provider_models"),
    )


class ProviderTierAccess(Base):
    __tablename__ = "provider_tier_access"

    provider_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("providers.id", ondelete="CASCADE"),
        nullable=False,
    )
    tier: Mapped[str] = mapped_column(Text, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint(
            "provider_id", "tier", name="pk_provider_tier_access"
        ),
    )


class ProviderModelTierAccess(Base):
    """Optional finer-grained whitelist; falls back to provider_tier_access."""

    __tablename__ = "provider_model_tier_access"

    provider_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("providers.id", ondelete="CASCADE"),
        nullable=False,
    )
    model_id: Mapped[str] = mapped_column(Text, nullable=False)
    tier: Mapped[str] = mapped_column(Text, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint(
            "provider_id",
            "model_id",
            "tier",
            name="pk_provider_model_tier_access",
        ),
    )


# ---------------------------------------------------------------------------
# Jobs / references / images / sessions
# ---------------------------------------------------------------------------


class Job(Base):
    __tablename__ = "jobs"

    # Internal id used for FK relationships ('job_' + nanoid).
    id: Mapped[str] = mapped_column(Text, primary_key=True)
    # Public-facing short id ('j_' + 12 chars) — what the frontend stores.
    hash_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)

    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id"), nullable=False
    )
    tier_at_submit: Mapped[str] = mapped_column(Text, nullable=False)
    seq_no: Mapped[int] = mapped_column(Integer, nullable=False)
    set_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    session_id: Mapped[str | None] = mapped_column(Text, nullable=True)

    model: Mapped[str] = mapped_column(Text, nullable=False)
    params_json: Mapped[str] = mapped_column(Text, nullable=False)
    flags_json: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'{}'")
    )
    client_request_id: Mapped[str | None] = mapped_column(Text, nullable=True)

    status: Mapped[str] = mapped_column(Text, nullable=False)
    status_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    provider_used: Mapped[str | None] = mapped_column(Text, nullable=True)
    retries: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    cost_cny: Mapped[float] = mapped_column(
        nullable=False, server_default=text("0")
    )

    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    queued_at: Mapped[datetime | None] = mapped_column(nullable=True)
    dispatched_at: Mapped[datetime | None] = mapped_column(nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED','DELETED')",
            name="ck_jobs_status",
        ),
        UniqueConstraint("user_id", "seq_no", name="idx_jobs_user_seq"),
        Index("idx_jobs_user_updated", "user_id", "updated_at"),
        Index("idx_jobs_user_status", "user_id", "status"),
        Index("idx_jobs_status_created", "status", "created_at"),
        Index("idx_jobs_set", "set_id"),
    )


class JobReference(Base):
    __tablename__ = "job_references"

    job_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    ref_order: Mapped[int] = mapped_column(Integer, nullable=False)
    filename: Mapped[str] = mapped_column(Text, nullable=False)
    mime: Mapped[str] = mapped_column(Text, nullable=False)
    rel_path: Mapped[str] = mapped_column(Text, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("job_id", "ref_order", name="pk_job_references"),
    )


class Image(Base):
    __tablename__ = "images"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    job_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    img_order: Mapped[int] = mapped_column(Integer, nullable=False)
    original_path: Mapped[str] = mapped_column(Text, nullable=False)
    thumb_path: Mapped[str] = mapped_column(Text, nullable=False)
    width: Mapped[int] = mapped_column(Integer, nullable=False)
    height: Mapped[int] = mapped_column(Integer, nullable=False)
    format: Mapped[str] = mapped_column(Text, nullable=False)
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    starred: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (Index("idx_images_job", "job_id", "img_order"),)


class Session(Base):
    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (Index("idx_sessions_user", "user_id", "updated_at"),)


class SessionJob(Base):
    """Many-to-many join: a job can be bound into a session."""

    __tablename__ = "session_jobs"

    session_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    job_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )

    __table_args__ = (
        PrimaryKeyConstraint("session_id", "job_id", name="pk_session_jobs"),
    )


# ---------------------------------------------------------------------------
# Billing
# ---------------------------------------------------------------------------


class BillingLedger(Base):
    __tablename__ = "billing_ledger"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    job_id: Mapped[str] = mapped_column(Text, nullable=False)
    provider_id: Mapped[str] = mapped_column(Text, nullable=False)
    cost_cny: Mapped[float] = mapped_column(nullable=False)
    image_count: Mapped[int] = mapped_column(Integer, nullable=False)
    deducted_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (
        Index("idx_ledger_provider_time", "provider_id", "deducted_at"),
    )


# ---------------------------------------------------------------------------
# Announcements
# ---------------------------------------------------------------------------


class Announcement(Base):
    __tablename__ = "announcements"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    content_kind: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)

    audience_kind: Mapped[str] = mapped_column(Text, nullable=False)
    audience_data: Mapped[str | None] = mapped_column(Text, nullable=True)

    starts_at: Mapped[datetime] = mapped_column(nullable=False)
    ends_at: Mapped[datetime | None] = mapped_column(nullable=True)
    dismissable: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1")
    )
    priority: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )

    created_by: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )


class AnnouncementRead(Base):
    __tablename__ = "announcement_reads"

    user_id: Mapped[str] = mapped_column(Text, nullable=False)
    announcement_id: Mapped[str] = mapped_column(Text, nullable=False)
    read_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (
        PrimaryKeyConstraint(
            "user_id", "announcement_id", name="pk_announcement_reads"
        ),
    )


# ---------------------------------------------------------------------------
# Login attempts / audit log / config / disk usage
# ---------------------------------------------------------------------------


class LoginAttempt(Base):
    __tablename__ = "login_attempts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    username: Mapped[str] = mapped_column(Text, nullable=False)
    ip: Mapped[str | None] = mapped_column(Text, nullable=True)
    success: Mapped[int] = mapped_column(Integer, nullable=False)
    attempted_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (
        Index("idx_login_attempts_user_time", "username", "attempted_at"),
    )


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    actor_user_id: Mapped[str] = mapped_column(Text, nullable=False)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    target_kind: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    payload_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    ip: Mapped[str | None] = mapped_column(Text, nullable=True)
    ts: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )

    __table_args__ = (Index("idx_audit_actor_ts", "actor_user_id", "ts"),)


class Config(Base):
    __tablename__ = "config"

    key: Mapped[str] = mapped_column(Text, primary_key=True)
    value_json: Mapped[str] = mapped_column(Text, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    updated_by: Mapped[str | None] = mapped_column(Text, nullable=True)


class DiskUsage(Base):
    __tablename__ = "disk_usage"

    scope: Mapped[str] = mapped_column(Text, primary_key=True)
    bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    job_count: Mapped[int] = mapped_column(Integer, nullable=False)
    refreshed_at: Mapped[datetime] = mapped_column(nullable=False)
