"""Initial schema — all tables defined in the design doc §14.

Revision ID: 0001_init
Revises:
Create Date: 2026-04-27

This migration is intentionally hand-curated rather than autogenerated so
the table layout matches the design doc exactly. Future schema changes
must arrive in a new revision; do not edit this file.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_init"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ users
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Text(),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "today_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "today_reset_date",
            sa.Text(),
            server_default=sa.text("(date('now','+8 hours'))"),
            nullable=False,
        ),
        sa.Column("override_soft_quota", sa.Integer(), nullable=True),
        sa.Column("override_hard_quota", sa.Integer(), nullable=True),
        sa.Column(
            "last_seq_no", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("role IN ('admin','user')", name="ck_users_role"),
        sa.CheckConstraint(
            "status IN ('active','disabled','deleted')", name="ck_users_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "idx_users_status_tier", "users", ["status", "tier"], unique=False
    )

    # ------------------------------------------------------------------ tiers
    op.create_table(
        "tiers",
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("max_queue", sa.Integer(), nullable=False),
        sa.Column("soft_quota", sa.Integer(), nullable=False),
        sa.Column("hard_quota", sa.Integer(), nullable=False),
        sa.Column("slo_p95_ms", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tier IN ('vip','premium','standard','free')", name="ck_tiers_tier"
        ),
        sa.PrimaryKeyConstraint("tier"),
    )

    # -------------------------------------------------------------- providers
    op.create_table(
        "providers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("adapter_type", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("api_key_enc", sa.Text(), nullable=False),
        sa.Column("cost_per_image_cny", sa.Float(), nullable=False),
        sa.Column("initial_balance_cny", sa.Float(), nullable=False),
        sa.Column("balance_cny", sa.Float(), nullable=False),
        sa.Column(
            "enabled", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "max_concurrency",
            sa.Integer(),
            server_default=sa.text("10"),
            nullable=False,
        ),
        sa.Column(
            "rpm_limit",
            sa.Integer(),
            server_default=sa.text("600"),
            nullable=False,
        ),
        sa.Column(
            "circuit_state",
            sa.Text(),
            server_default=sa.text("'healthy'"),
            nullable=False,
        ),
        sa.Column("cooldown_until", sa.DateTime(), nullable=True),
        sa.Column("recent_calls_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "circuit_state IN ('healthy','open','half_open','drained','disabled')",
            name="ck_providers_circuit_state",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "provider_models",
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("capabilities_json", sa.Text(), nullable=False),
        sa.Column(
            "enabled", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "provider_id", "model_id", name="pk_provider_models"
        ),
    )

    op.create_table(
        "provider_tier_access",
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "provider_id", "tier", name="pk_provider_tier_access"
        ),
    )

    op.create_table(
        "provider_model_tier_access",
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "provider_id",
            "model_id",
            "tier",
            name="pk_provider_model_tier_access",
        ),
    )

    # ------------------------------------------------------------------- jobs
    op.create_table(
        "jobs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("hash_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("tier_at_submit", sa.Text(), nullable=False),
        sa.Column("seq_no", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Text(), nullable=True),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column(
            "flags_json", sa.Text(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("client_request_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("provider_used", sa.Text(), nullable=True),
        sa.Column(
            "retries", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cost_cny", sa.Float(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED','DELETED')",
            name="ck_jobs_status",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash_id"),
        sa.UniqueConstraint("user_id", "seq_no", name="idx_jobs_user_seq"),
    )
    op.create_index(
        "idx_jobs_user_updated", "jobs", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "idx_jobs_user_status", "jobs", ["user_id", "status"], unique=False
    )
    op.create_index(
        "idx_jobs_status_created", "jobs", ["status", "created_at"], unique=False
    )
    op.create_index("idx_jobs_set", "jobs", ["set_id"], unique=False)

    op.create_table(
        "job_references",
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("ref_order", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("mime", sa.Text(), nullable=False),
        sa.Column("rel_path", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "ref_order", name="pk_job_references"),
    )

    op.create_table(
        "images",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("img_order", sa.Integer(), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("thumb_path", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "starred", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_images_job", "images", ["job_id", "img_order"], unique=False)

    # --------------------------------------------------------------- sessions
    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sessions_user", "sessions", ["user_id", "updated_at"], unique=False
    )

    op.create_table(
        "session_jobs",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id", "job_id", name="pk_session_jobs"),
    )

    # ---------------------------------------------------------- billing ledger
    op.create_table(
        "billing_ledger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.Text(), nullable=False),
        sa.Column("cost_cny", sa.Float(), nullable=False),
        sa.Column("image_count", sa.Integer(), nullable=False),
        sa.Column(
            "deducted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ledger_provider_time",
        "billing_ledger",
        ["provider_id", "deducted_at"],
        unique=False,
    )

    # ---------------------------------------------------------- announcements
    op.create_table(
        "announcements",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("content_kind", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("audience_kind", sa.Text(), nullable=False),
        sa.Column("audience_data", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column(
            "dismissable", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "priority", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "announcement_reads",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("announcement_id", sa.Text(), nullable=False),
        sa.Column(
            "read_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "announcement_id", name="pk_announcement_reads"
        ),
    )

    # ---------------------------------------- login_attempts / audit / config
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("success", sa.Integer(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_login_attempts_user_time",
        "login_attempts",
        ["username", "attempted_at"],
        unique=False,
    )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_kind", sa.Text(), nullable=True),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column(
            "ts",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_actor_ts", "audit_log", ["actor_user_id", "ts"], unique=False
    )

    op.create_table(
        "config",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )

    op.create_table(
        "disk_usage",
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("scope"),
    )


def downgrade() -> None:
    op.drop_table("disk_usage")
    op.drop_table("config")
    op.drop_index("idx_audit_actor_ts", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_login_attempts_user_time", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_table("announcement_reads")
    op.drop_table("announcements")
    op.drop_index("idx_ledger_provider_time", table_name="billing_ledger")
    op.drop_table("billing_ledger")
    op.drop_table("session_jobs")
    op.drop_index("idx_sessions_user", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("idx_images_job", table_name="images")
    op.drop_table("images")
    op.drop_table("job_references")
    op.drop_index("idx_jobs_set", table_name="jobs")
    op.drop_index("idx_jobs_status_created", table_name="jobs")
    op.drop_index("idx_jobs_user_status", table_name="jobs")
    op.drop_index("idx_jobs_user_updated", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("provider_model_tier_access")
    op.drop_table("provider_tier_access")
    op.drop_table("provider_models")
    op.drop_table("providers")
    op.drop_table("tiers")
    op.drop_index("idx_users_status_tier", table_name="users")
    op.drop_table("users")
