"""Request / response shapes for ``app.api.sessions``.

Sessions are user-owned tags that group jobs across multiple Generate
calls (design doc §6.6). The shape is small on purpose: a session has
a name and is associated with zero or more jobs through the
``session_jobs`` join table.

Field choices:

- ``id`` is the canonical ``sess_<10>`` form generated by
  :func:`app.utils.ids.new_session_id`. We expose it to the frontend
  rather than an opaque uuid because it is also stored on
  ``jobs.session_id`` and shows up in archive filters.
- ``name`` is required and trimmed; empty / whitespace-only names are
  rejected by the schema rather than the route handler so the error
  is uniform with every other 422 in the project.
- ``image_count`` is computed at read time from the join table; it is
  not a DB column. Including it in the response avoids forcing the
  frontend to make a follow-up call to render the session list.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Shared name validation helper
# ---------------------------------------------------------------------------


def _normalise_name(value: str) -> str:
    """Trim whitespace and reject empty names.

    We strip *and then* validate so a name like ``"  Editorial Cover  "``
    becomes the canonical ``"Editorial Cover"``; otherwise admins
    diffing the audit log would see surface-level differences that
    don't matter.
    """
    if not isinstance(value, str):
        raise ValueError("name must be a string")
    stripped = value.strip()
    if not stripped:
        raise ValueError("name cannot be empty")
    return stripped


# ---------------------------------------------------------------------------
# Requests
# ---------------------------------------------------------------------------


class SessionCreateRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=80)

    @field_validator("name")
    @classmethod
    def _trim(cls, v: str) -> str:
        return _normalise_name(v)


class SessionPatchRequest(BaseModel):
    """Partial update — only ``name`` is mutable today."""

    name: str | None = Field(default=None, min_length=1, max_length=80)

    @field_validator("name")
    @classmethod
    def _trim(cls, v: str | None) -> str | None:
        if v is None:
            return None
        return _normalise_name(v)


# ---------------------------------------------------------------------------
# Responses
# ---------------------------------------------------------------------------


class SessionResponse(BaseModel):
    """Single session view used by the list, create and patch routes."""

    id: str
    name: str
    image_count: int = 0
    created_at: datetime
    updated_at: datetime


class SessionListResponse(BaseModel):
    sessions: list[SessionResponse]
